name: Build and Publish CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'quotron/cli/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version
      id: version
      run: |
        cd quotron/cli
        VERSION=$(git rev-parse --short HEAD)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Build CLI
      run: |
        cd quotron/cli
        go build -o quotron-linux -v ./cmd/main
        chmod +x quotron-linux
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: cli-v${{ steps.version.outputs.version }}
        name: Quotron CLI v${{ steps.version.outputs.version }}
        body: |
          Quotron CLI binary for Linux
          
          Automatically built from commit ${{ steps.version.outputs.version }}
        files: |
          quotron/cli/quotron-linux
        draft: false